### ISSUE TITLE
installation instructions for windows, mac, etc.

### ISSUE THREAD

**Issue by sheppard** [wq/wq#11]
Please comment on this issue if you would like me to document the process for installing and running Django and wq on platforms other than Ubuntu Linux.

The current installation instructions are available at http://wq.io/docs/setup.

**Comment by aaronlee1** [comment]
Hey Andrew,

I think this is a really great platform option, I am new the the development community and am having some trouble getting the wq framework installed on my windows system.

It would be great to have some documentation for that if possible. Thanks,

**Comment by sheppard** [comment]
Thanks for the ping - I'll move this up on the priority list.

**Comment by sheppard** [comment]
The new "local" setup docs mostly address this issue:

https://wq.io/1.1/docs/setup-local
