### ISSUE TITLE
nginx + gunicorn/uwsgi deployement setup

### ISSUE THREAD

**Issue by auvipy** [wq/wq#13]
using nginx with wsgi is considered best practice now. so documenting that will be very useful

**Comment by sheppard** [comment]
Sure, we can add a section for that.  I haven't worked with nginx myself but if someone wants to put some docs together I can take a look.

**Comment by chlarsen** [comment]
Dear All,
I am currently in the process of deploying the wq framework on OpenBSD (and use equally often FreeBSD). OpenBSD has its own HTTPd web server, which does FastCGI; on FreeBSD I use Nginx.
I have managed to install wq on both platforms, but but truly shy away from deploying huge and clunky Apache for wq, only. I will be more than happy to help with the documentation, and know how to stick uWSGI or Gunicorn into Nginx (and will tame HTTPd, too). However, I seem to get stuck at a suitable uwsgi-compatible app file/location, while Gunicorn complains of not finding a wsgi module. 
I am probably just looking at the wrong things - any ideas or hints?
Thank you!
Chris
