### ISSUE TITLE
wq - How to get started

### ISSUE THREAD

**Issue by chlarsen** [wq/wq#18]
The wq framework looks incredibly promising, but for those that are not insiders already, it seems to be really hard to get started. After having successfully installed the framework, it is really not clear, where to proceed, how to create forms/questionnaires, etc. There seems to be a sore lack of documentation for beginners in wq to get going - which may be regarded as a big pity. wq deserves, IMHO, better.
Thanks a lot for any hints!
Chris

**Comment by sheppard** [comment]
Thanks for your interest in wq!  We'll be working on expanding the "getting started" documentation over the next couple of months, so keep an eye out for updates.  In the meantime, you might be interested in the [Species Tracker](https://github.com/powered-by-wq/species.wq.io) for a working example of how an app is put together.

wq is a MVC-like framework in that you start by defining your data model (and REST API) before making any actual forms.  So, the typical workflow for getting started is something like this:

1. `wq start [projectname]`
2. Create a folder db/[appname] for your models.py and rest.py (see the db/exampleapp folder created by `wq start`).  Add [appname] to your `INSTALLED_APPS` in db/[projectname]/settings.py
3. Define Django Model classes in models.py: https://docs.djangoproject.com/en/1.8/topics/db/models/.  In the simplest case, a model will have the same fields as the form you're planning on creating.
4. Use Django's built in "migrate" tool to create database tables in PostgreSQL corresponding to your model classes: https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-migrate
5. Create a rest.py and register the model class with the wq.db REST API: https://wq.io/docs/router.  Visit /config.json and /[modelname]s.json to see that the model was registered.
6. Create HTML templates for "list", "detail" and "edit" views (see https://wq.io/docs/template). The example templates provided by the wq start command should give you an idea what's needed.

**Comment by chlarsen** [comment]
Thank you so much, Andrew, for your quick and comprehensive response!
Hugely appreciated.
Best regards from Sierra Leone,
Chris

On 02/09/15 15:05, S. Andrew Sheppard wrote:
> Thanks for your interest in wq! We'll be working on expanding the
> "getting started" documentation over the next couple of months, so keep
> an eye out for updates. In the meantime, you might be interested in the
> Species Tracker <https://github.com/powered-by-wq/species.wq.io> for a
> working example of how an app is put together.
> 
> wq is a MVC-like framework in that you start by defining your data model
> (and REST API) before making any actual forms. So, the typical workflow
> for getting started is something like this:
> 
>  1. |wq start [projectname]|
>  2. Create a folder db/[appname] for your models.py and rest.py (see the
>     db/exampleapp folder created by |wq start|). Add [appname] to your
>     |INSTALLED_APPS| in db/[projectname]/settings.py
>  3. Define Django Model classes in models.py:
>     https://docs.djangoproject.com/en/1.8/topics/db/models/. In the
>     simplest case, a model will have the same fields as the form you're
>     planning on creating.
>  4. Use Django's built in "migrate" tool to create database tables in
>     PostgreSQL corresponding to your model classes:
>     https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-migrate
> 
>  5. Create a rest.py and register the model class with the wq.db REST
>     API: https://wq.io/docs/router. Visit /config.json and
>     /[modelname]s.json to see that the model was registered.
>  6. Create HTML templates for "list", "detail" and "edit" views (see
>     https://wq.io/docs/template). The example templates provided by the
>     wq start command should give you an idea what's needed.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wq/wq/issues/18#issuecomment-137116268>.
> 

-- 
Dr Christoph H. Larsen
synaLinQ
296/33 Lương Định Của, Ngọc Hội 2, Vĩnh Ngọc
Nha Trang, Khanh Hoa, Vietnam
Mobile:	+84-98-9607357 (Vietnam)
	+254-751-204706 (Kenya)
	+256-790-527900 (Uganda)
Fax:	+49-231-292734790
E-mail:	christoph.larsen@synalinq.com
Skype:	christoph.larsen

**Comment by olivierdalang** [comment]
Hi! 

I'm getting started too and  it looks great so far!! 
I was wondering if having auto generated templates is possible? 
The possibility to define custom template is great, but for early development (or simple cases),  having a pure model driven app is extremely convenient. I love django admin for that, and am so sad it's not Ajax based to spare bandwidth. 

Bests! 

Olivier

(sorry to discuss this in a github issue,  maybe it's worth opening a mailing list for the project? )

**Comment by sheppard** [comment]
Thanks for the comment.  I think there is a way we could generate templates via a command line tool in wq.start (see wq/wq-django-template#18).  I also created an issue here (#20) for starting up a mailing list, until then feel free to keep using Github issues to discuss.

**Comment by sheppard** [comment]
I just released an alpha version of wq 1.0, which includes some default model-driven auto-generated templates like the Django admin, and a tool to create both models and templates from an [XLSForm](http://xlsform.org) definition.  This should help make it a bit easier to get started.

https://wq.io/1.0/docs/setup
