### ISSUE TITLE
wq start command broken

### ISSUE THREAD

**Issue by jfw** [wq/wq#23]
Running wq start as per the getting started docs doesn't work. I get an error no matter the project name given:
```
$ wq start mud
Usage: wq [OPTIONS] COMMAND [ARGS]...

Error: No such command "mud".
```

The only projectname that works is "start", but that only creates a project named "start". Using python3.3, a fresh virtualenv with only wq & dependencies installed.

**Comment by sheppard** [comment]
Looks like something has changed in the newest version of [click](http://click.pocoo.org), which the `wq` command uses internally.  I'll need to do some more investigation, but for now you can get around it by installing an older version:
```bash
pip install click==5.1
```

**Comment by sheppard** [comment]
I went ahead and released a new version of `wq.core` that explicitly requests the older Click version so this shouldn't be an issue anymore.  Thanks for reporting this!
