### ISSUE TITLE
Broken link in docs: Example templates

### ISSUE THREAD

**Issue by tomaszn** [wq/wq#25]
URL: https://wq.io/1.0/docs/templates
Chapter: Examples, link to "pre-defined Mustache template examples"

**Comment by sheppard** [comment]
Yes, the new link is https://github.com/wq/wq-django-template/tree/master/templates, but that section needs to be rewritten anyway in light of the wq 1.0 changes.  The wq.start 0.8 template included a couple example models together with some usable list/detail/edit templates.  Now that templates can be generated automatically, I removed the default models as well as the example templates.  So the biggest thing needed now is to fully document the usage of `wq maketemplates` and [xlsform-converter](https://github.com/wq/xlsform-converter).

Still, there is some value in having plain list/detail/edit templates available as a reference.  We could point to the [Species Tracker templates](https://github.com/powered-by-wq/species.wq.io/tree/master/templates) which are similar to the old wq start templates.  The Species Tracker templates are now automatically generated by xlsform-converter as well, but I kept them in the repository anyway to make it easier to use them as a reference.
