### ISSUE TITLE
Expired HTTPS certificate on https://wq.io/

### ISSUE THREAD

**Issue by tomaszn** [wq/wq#28]
When accessing the site my web browser reports:
```
wq.io uses an invalid security certificate.
The certificate expired on October 30, 2017, 8:14 PM.
The current time is November 4, 2017, 9:20 PM.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by sheppard** [comment]
Thanks, should be working now.  Leaving this open as a reminder to get the renewal script to run automatically.

**Comment by tomaszn** [comment]
This also applies to https://try.wq.io

**Comment by sheppard** [comment]
Thanks, I fixed try.wq.io and enabled automatic renewals (by upgrading to the latest certbot package).
