### ISSUE TITLE
How to implement dependent/chained drop down list in edit form.

### ISSUE THREAD

**Issue by mayank1989soni** [wq/wq#29]
I started working on wq quite recently  and felt very promising for developing data collection apps.But I have a requirement of adding a chained dropdown in the edit form when the user selects Country, States should be filtered in the corresponding drop down. like Country USA State CA,MI,TX.....Please guide me.
Thanks

**Comment by sheppard** [comment]
See https://github.com/wq/wq.app/issues/106 for discussion.
