### ISSUE TITLE
Running wq from within a Sub-URI

### ISSUE THREAD

**Issue by chlarsen** [wq/wq#31]
As I am slowly, but surely making progress with running wq from within OpenBSD, using HTTPd, Relayd and uWSGI, I need some advice on how to run wq from inside a sub-URI, such as "https://my.domain/wq". Seemingly it is not enough to configure the webserver accordingly. Is thereany setting that I am missing?
Thank you so much!
Chris

**Comment by chlarsen** [comment]
Dear Andrew,
The above issue is still on, and a bit of a show stopper, because I cannot have any subdomain for wq (as in wq.my.domain) given the current setting.
As I said, the generic Django stuff works, but even adding:
``````
FORCE_SCRIPT_NAME = '/wq_ghs_idi'
BASE_PATH = '/wq_ghs_idi'
STATIC_URL = BASE_PATH + 'static/'
MEDIA_URL = STATIC_URL + 'media/'
``````
does not bring any joy for wq itself.
Am I missing anything silly?
Thank you!
Chris

**Comment by sheppard** [comment]
The main two areas where this is important:
 1. rendering templates with links
 2. routing those links when clicked

Within the client (wq.app), you can configure the router by setting the base url in `[projectname]/config.js`:

```javascript
config.router = {
    'base_url': '/wq_ghs_idi'
};
```

This setting is automatically copied to the template renderer.

On the server (wq.db), you should be able to use normal Django (and/or webserver) settings for the router.  However, I haven't yet configured the template renderer to pick up that setting (see https://github.com/wq/wq.db/issues/53).  Essentially there needs to be a `{{rt}}` variable in the context which will be picked up by the templates.

A workaround would be to create a custom context processor and register it in your settings:

```python
# [appname]/context_processors.py```
def route_base_url(request):
     return {'rt': '/wq_ghs_idi'}
```

```python
# [projectname]/settings/base.py
TEMPLATES[0]['OPTIONS']['context_processors'] += (
    'appname.context_processors.route_base_url',
)
```

Another workaround would be to replace all instances of {{rt}} in the templates with your base URL.

**Comment by chlarsen** [comment]
Thank you so much, Andrew. I am glad to see that I am actually blowing into the same horn as others, regarding readiness for sub-URI deployment. Let me have a look at the workarounds nevertheless. 
Cheers!

**Comment by sheppard** [comment]
This is working in [wq.db 1.1.3](https://github.com/wq/wq.db/releases/tag/v1.1.3) (with a related fix in [wq.app 1.1.2](https://github.com/wq/wq.app/releases/tag/v1.1.2)).
