### ISSUE TITLE
pip installation of py-mini-racer fails

### ISSUE THREAD

**Issue by chlarsen** [wq/wq#32]
Dear Andrew,
Just to let you know that the installation of wq 1.1.0 seems to fail due to an error with py-mini-racer (which is a new component of your software suite). Please see [here](https://github.com/sqreen/PyMiniRacer/issues/57).
I hope they get this sorted, but maybe you have an idea or two?
Thank you so much!
Chris

**Comment by chlarsen** [comment]
Dear Andrew,
The issue really lies with py-mini-racer and its inability to fetch v8. 
Cutting through all this, can I still get a "proper" wq instance by issuing:
pip3 install https://github.com/wq/wq.db/archive/master.zip
from within the virtual environment, or will this get me into trouble?
Thank you for your guidance,
Chris

**Comment by chlarsen** [comment]
Dear Andrew,
I am not sure, whether you have already had a chance to follow up on the above conversation re. python-mini-racer, but in essence, there seems to be an issue with the pyton-mini-racer installation script that requires python2. As wq requires python3, things go wrong. While the python-mini-racer developer is kindly looking into this issue, is there any way to do the wq thing without python-mini-racer? Or how did you manage to install it? I have both python 2 and python3 installed on FreeBSD, but they are separated, last not least courtesy of their respective virtual environments.
Any thoughts or ideas are highly appreciated.
Chris

**Comment by sheppard** [comment]
I made some adjustments to python-requirejs that will skip the py-mini-racer dependency on platforms that don't yet have a precompiled wheel.  I will release the new version after some testing, but for now you can try this:

```bash
pip install https://github.com/wq/python-requirejs/archive/master.zip
pip install wq
```

**Comment by chlarsen** [comment]
Dear Andrew,
Thank you so much for this - this did the trick! Hugely appreciated!
Chris


On Tuesday, July 10, 2018 21:28 +07, "S. Andrew Sheppard" <notifications@github.com> wrote:
 
I made some adjustments to python-requirejs that will skip the py-mini-racer dependency on platforms that don't yet have a precompiled wheel. I will release the new version after some testing, but for now you can try this:pip install https://github.com/wq/python-requirejs/archive/master.zip
pip install wq
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--
Dr Christoph H. Larsen
synaLinQ
Mobile: +84-98-9607357 (Vietnam)
        +254-701-279511 (Kenya)
        +265-998-393993 (Malawi)
        +49-176-96456254 (Germany)
Fax: +49-231-292734790
E-mail: christoph.larsen@synalinq.com
Skype: christoph.larsen

**Comment by sheppard** [comment]
I released the updated python-requirejs to PyPI so this should work by default now.
