### ISSUE TITLE
GDAL_LIBRARY_PATH setting missing

### ISSUE THREAD

**Issue by babylonlin** [wq/wq#34]
Hi I am new to wq framework. During the database migrate (windows 10 x64) manage.py migrate step I can not go further. 
The error is as following: -  Could not find the GDAL library and I need to define GDAL_LIBRARY_PATH. I installed  OSGeo4W for windows and set GDAL_LIBRARY_PATH=os.path.join( "C:", "OSGeo4W", "bin" ) in base.py.  Then I got the error WinError 126 Modul can not be found:
  File "C:\Users\XXX\Envs\wq-learn\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 47, in <module>
    lgdal = CDLL(lib_path)
  File "c:\users\XXXX\anaconda3\Lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

I use python 3.7 and pip 18

**Comment by babylonlin** [comment]
I just tried on a virtual machine with ubuntu 18.04 installed. Same error with GDAL library.

**Comment by sheppard** [comment]
Thanks for reporting this.  I removed the hard dependency on GDAL in the latest version so now you should be able to use wq without it.  I also updated the documentation to make it clearer how to install GDAL if you do need it:

https://wq.io/1.1/docs/setup-local
