### ISSUE TITLE
Customizing form widgets

### ISSUE THREAD

**Issue by fccoelho** [wq/wq#46]
Is there a way to customize form field widgets? I found the `TimeField` widget not very nice and the `BooleanField` Allows for pretty much anything(its being rendered as a text input widget instead of a checkbox).

**Comment by sheppard** [comment]
This was possible before, but is significantly improved in [wq 1.3 alpha](https://github.com/wq/wq/releases/tag/v1.3.0a1).  The new [@wq/react](https://github.com/wq/wq.app/tree/master/packages/react) + [@wq/material](https://github.com/wq/wq.app/tree/master/packages/material) UI renderer provides nicer default widgets, based on [Material UI](https://material-ui.com) and [Material UI Pickers](https://material-ui-pickers.dev/).  It also provides a better mechanism for customizing the defaults - see the new [Input Components](https://github.com/wq/wq.app/tree/master/packages/react#input-components) documentation for details.
