### ISSUE TITLE
wq addform

### ISSUE THREAD

**Issue by roberttodor** [wq/wq#48]
I just installed Wq for local develpoment. Everything seems to work fine, but when I use "wq addform" it dosen't take the xlsx file name, it use name "data". Of course it fails with the second "wq addform" beacuse name "data "  was registred for another model.  I thought it was because of DB and tested with postgresql and spatialite, and got the same issue.

**Comment by roberttodor** [comment]
The problem is a new version of pyxform. Wq works pyxform version 0.15.1 and fails with version 1.1.0.

**Comment by sheppard** [comment]
This is fixed in [xlsconv 1.2.0](https://github.com/wq/xlsform-converter/releases/v1.2.0).
