### ISSUE TITLE
Add image problem from browser

### ISSUE THREAD

**Issue by roberttodor** [wq/wq#50]
I have a ImageField but no way to add a file.  I expected something like a pop up to add file, but nothing.
![imagen](https://user-images.githubusercontent.com/38351057/99521392-a714f800-2994-11eb-80d5-ae8950898ffd.png)

![imagen](https://user-images.githubusercontent.com/38351057/99521608-ecd1c080-2994-11eb-8f5b-9870bbcec1ae.png)

**Comment by sheppard** [comment]
The underlying support was mostly there but I hadn't integrated a UI widget.  I found https://github.com/Yuvaleros/material-ui-dropzone which seems to work pretty well.
