### ISSUE TITLE
Doc Error in  wq/docs/guides/setup-wq-with-sqlite.md 

### ISSUE THREAD

**Issue by mhfreund** [wq/wq#53]
In wq/docs/guides/setup-wq-with-sqlite.md :
...
wq create myproject .
...
gives:
Error: No such command "create".
Please change to start

**Comment by sheppard** [comment]
Thanks for reporting this.  The content under docs/ is for the next release, where the command name will change.  I updated the docs to explicitly note the old name.

**Comment by sheppard** [comment]
Closing this as the new release is now available on PyPI.
