### ISSUE TITLE
wq_label_template causes `Uncaught ReferenceError: $ is not defined`

### ISSUE THREAD

**Issue by olivierdalang** [wq/wq#55]
Hi !

Congrats for the new beta ! Looking forward to diving again into WQ :-)

One issue I encountered quite early is an `Uncaught ReferenceError: $ is not defined` as soon as I define the `wq_label_template` attribute one my model classes.

By the way, I'd suggest adding the __str__ and wq_label_template to the docs quite early (in https://wq.io/guides/describe-your-data-model#option-2-django-model-syntax) as it's very important to get usable and good looking results, and for some reason it took me ages to find https://wq.io/guides/configure-ids-and-labels.

```python
#models.py

class Member(models.Model):
    name = models.CharField(max_length=255)
    group = models.ForeignKey(Group, on_delete=models.PROTECT)
    wq_label_template = "{{name}}"
    def __str__(self):
        return self.name
...
```

```html
# place that throws the error in the generated HTML
...
      <script>
        $(document).ready(function() {
          $('form').ajaxForm();
        });
      </script>
...
```

**Comment by olivierdalang** [comment]
Sorry for the noise, actually I think it's something else (looks like some misconfiguration of the reverse proxy)

**Comment by sheppard** [comment]
https://wq.io/gudes/configure-ids-and-labels is relatively new, so it's not well linked from the older docs yet.  If you want to add a link from https://wq.io/guides/describe-your-data-model, you can click the floating edit button at the bottom right to start up a PR.
