### ISSUE TITLE
./deploy error due to missing .js extensions

### ISSUE THREAD

**Issue by presocratics** [wq/wq#58]
I am following the [How To: Set up wq with SQLite](https://wq.io/guides/setup-wq-with-sqlite) guide and running into errors when [deploying the Django server](https://wq.io/guides/setup-wq-with-sqlite#start-django-server) with node enabled.  When I run `deploy.sh` with node and GIS disabled, I am able to deploy.  However, enabling node (keeping GIS disabled) results in the following error.  Any thoughts on how to proceed?

```
(venv) [marty@peach withnode]$ ./deploy.sh 0.0.1
System check identified some issues:

WARNINGS:
rest.ContentType: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
    HINT: Configure the DEFAULT_AUTO_FIELD setting or the RestConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Application version: 0.0.1
Generating icons for web: 180, 192, 512

> withnode@0.0.1 build /home/marty/dsa/withnode/app
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './App' in '/home/marty/wqtest/withnode/app/node_modules/@wq/material'
Did you mean 'App.js'?
BREAKING CHANGE: The request './App' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! withnode@0.0.1 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the withnode@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marty/.npm/_logs/2022-01-02T18_37_02_992Z-debug.log
```

**Comment by sheppard** [comment]
Looks like this is due to stricter ESM module resolution in webpack 5, which is included in [react-scripts 5](https://github.com/facebook/create-react-app/releases/tag/v5.0.0).  To fully address this I will need to make a new release of @wq/material and affected libraries with the extensions added for internal imports.

In the meantime, you can work around this by downgrading to react-scripts 4 before deploying:

```
cd app/
npm i react-scripts@4
cd ../
./deploy.sh 0.0.0
```

**Comment by presocratics** [comment]
Using react-scripts 4 fixed it.  Thanks.

**Comment by sheppard** [comment]
Closing now that wq.create 1.3 is released, which pins the react-scripts version.  (See wq/wq.app#130 for follow up.)
