### ISSUE TITLE
Incompatible with npm 7

### ISSUE THREAD

**Issue by alvaropascuaI** [wq/wq#59]
When I add a geo question type to form it returns an error 311 which is about react and I saw versions of my react packs and they are incompatible

![image](https://user-images.githubusercontent.com/97975075/149981511-5e3c90b1-86fa-488e-bcc7-59854d17b1bd.png)

![error_versiones](https://user-images.githubusercontent.com/97975075/149980457-65466591-37bb-402b-9eb2-3e69159d16be.JPG)

**Comment by sheppard** [comment]
It looks like `react-mapbox-gl`'s `peerDependencies` need to be updated.  In the meantime, as long as you only install the main `dependencies`, it should still work even though `react-mapbox-gl` has a different React version in `peerDependencies`.  Did you do something specific to install peer and/or dev dependencies separately?

**Comment by fed3ric0** [comment]
I install dependencies when u start and i do enable GIS and NPM, but if i only say that enable GIS, work well

**Comment by sheppard** [comment]
Actually, it looks like this is an incompatibility with npm 7.  This will be addressed in a future release, but for now wq's npm integration requires npm 6 or earlier.

**Comment by sheppard** [comment]
Fixed via wq/wq.app#131.
