### ISSUE TITLE
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'

### ISSUE THREAD

**Issue by bwcastillo** [wq/wq#61]
Hello, 

I am doing the [basic tutorial ](https://wq.io/guides/setup-wq-with-sqlite), and in the Initialize SQL section, when I run `python manage.py migrate`  I am having the next problem: `AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField`. I tried to install an oldest Django version because of there are a similar bug in [this Stackoverflow](https://stackoverflow.com/questions/73823743/attributeerror-module-rest-framework-serializers-has-no-attribute-nullboolea), but this didn't result.

How can I resolve this?
Thanks in advance.

**Comment by sheppard** [comment]
This due is an incompatibility with Django REST Framework 3.14.  It will be fixed in the upcoming wq 2.0 release, but for now I released [wq.db 1.3.1](https://github.com/wq/wq.db/releases/tag/v1.3.1) with an explicit dependency on DRF 3.13.

**Comment by bwcastillo** [comment]
@sheppard Thanks for the response, I really appreciate that.
